### ISSUE TITLE
Support for Better Combat.

### ISSUE THREAD

**Issue by MagmaSlime123** [Thelnfamous1/Combat-Next#1]
Title.

See https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus.

**Comment by Thelnfamous1** [comment]
Can you elaborate as to what support I'm supposed to provide? Many things are configurable on this end, and better combat's system is data-driven.

**Comment by MagmaSlime123** [comment]
Both mods do similar things with MC's modifiers, reach, and a lot of other things, etc.

**Comment by Thelnfamous1** [comment]
I understand, but are you experiencing any incompatibilities that you cannot fix yourself via configs for this mod or datapack entries for BC?

**Comment by ffuentesm** [comment]
> Both mods do similar things with MC's modifiers, reach, and a lot of other things, etc.

Combat next overrides Better Combat Reach. And you can disable the Reach tooltip on BC config.

**Comment by Thelnfamous1** [comment]
Closing as there doesn't seem to be a real issue to fix or enhancement to create.
