### ISSUE TITLE
Incompatibility With Modlist related to Mixin Extras 1.20.1

### ISSUE THREAD

**Issue by Nathanator9000** [Thelnfamous1/Combat-Next#11]
I was working on my modpack and noticed it was crashing and tried to isolate it. Unfortunately it seems to be multiple mods together that cause this crash. All these mods work together unless combined at the same time. They all work together unless all six are combined at once. It did not create a crash report, but I copied the log.

Mod List: Let's Do Api 1.2.8, Combat next 1.0.2, Moonlight 2.8.78, Caelus 3.1.0, Architectury 9.1.12, MIAPI 1.1.5

This is with the new version of Combat Next which was supposed to the mixin incompatibility.

[Launcher Log.txt](https://github.com/Thelnfamous1/Combat-Next/files/13795990/Launcher.Log.txt)

**Comment by RedPxnda** [comment]
Would be fixed in: https://github.com/Thelnfamous1/Combat-Next/pull/12

**Comment by Thelnfamous1** [comment]
Fixed in 1.20.1-1.0.3.
