### ISSUE TITLE
[1.20.1] Hurt sound still plays even when you disable shield changes in config

### ISSUE THREAD

**Issue by BugmanBugman** [Thelnfamous1/Combat-Next#9]
Title. The default shield block sound doesn't play when you block even after you revert shield changes to vanilla

**Comment by Thelnfamous1** [comment]
If you are blocking with a shield and the shield does not block all of the damage, the vanilla hurt sound will play instead of the shield block sound. This is how vanilla designed it, as you are still getting hurt.

**Comment by BugmanBugman** [comment]
I mean moreso that I turned off shield changes, so it blocks all damage again. But it still plays the hurt sound, not the block sound

**Comment by Thelnfamous1** [comment]
I wasn't able to recreate that during testing, specifically after removing the vanilla shield from the shield strength config list.
